### ISSUE TITLE
Update button on Edit Screen

### ISSUE THREAD

**Issue by henriquefacioli** [msandrini/achiever#31]
The "enviar" (send) button should be replaced with an "atualizar" (update) button if the data is already on server and is possible to edit it.
To do so, for now, it is need to do a mutation that will do like:
```
mutation updateTimeentries {
  delTimeEntry(date: '2018-01-25')
  addTimeEntry(TimeEntry)
}
```

but, to avoid inserting before deleting on async calls, maybe should create a new mutation `editTimeEntry(TimeEntry)` that would do that in one call. This should be implemented on `server/schema/resolver.js`

**Comment by msandrini** [comment]
This was done recently.
