### ISSUE TITLE
Alternate approach to the calls

### ISSUE THREAD

**Issue by msandrini** [msandrini/achiever#60]
I propose we do an alternate approach to the calls as they are now, to make the whole thing to be more easily in sync with the original system, and also to ease the maintainability. But it has a caveat: it might make the calls to update the times take much more time. 
We got to check the cost of that, writing this approach in a separate branch and comparing the final times to perform common operations.

The "new approach" consists of:
- On login: takes all values from the screen report and stores them.
- On update time: takes all values again from the screen report and replaces them on the storage.
- On day change: makes a call to the "single day" page on the original system, just to get the task and project (all other data will be there already). Maybe this can serve also to get the status of the day, regarding whether or not the day is locked.
- There would be no more "week call" and no icon for locked statuses
- We could have icons for o-tanjoubi (birthday), absence, things like this, instead of the lock icon.

**Comment by henriquefacioli** [comment]
Doings:
 - Populate allEntries on login
 - Delete IndexedDB on logout
 - Put on indexedDB at add time
 - If on edit page and no info on indexedDB, log user out
 - GET VALUES
    - Choose Day|Inint => Fetch info from especified day

**Comment by henriquefacioli** [comment]
- [x] Populate allEntries on login
- [x] If on auth page and no info on indexedDB, log user out
- [ ] Delete IndexedDB on logout: 
    **DB misses this feature**
- [ ] Put on indexedDB at add time:
    **WIP**
- [ ] Populate data on calendar
- [ ] Query date info on calendar day select (not fecthing from week)

**Comment by henriquefacioli** [comment]
Is there any chance of a specific date on achievo doesn't exist? Precisely: what should happen when you try to query a day that is not on allEntries (so not in indexedDB)

**Comment by henriquefacioli** [comment]
Some work on #72

**Comment by msandrini** [comment]
+1 for Henrique's work, but this is implemented already.
