### ISSUE TITLE
Different ways of passing data on project and activity

### ISSUE THREAD

**Issue by henriquefacioli** [msandrini/achiever#61]
At Edit.jsx, while `onSetActivity` expects the raw value (id) from the activity, `onSetProjectPhase` expects an object {id: id}.
Is there a reason? If not, should we standardize then both?

**Comment by msandrini** [comment]
The answers are, respectively, *no* and *yes* :)

**Comment by msandrini** [comment]
In my view, for this case there is no reason to send an object like `{ id: 0 }`, it would only make sense if we were to send other things together within this object.

**Comment by henriquefacioli** [comment]
#64
